version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: afterlib
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: afterlib
    ports:
      - '5432:5432'
    networks:
      - backend

  pgloader:
    image: dimitri/pgloader:latest
    command: ['tail', '-F', '-n0', '/etc/hosts']
    depends_on:
      - postgres
      - mysql
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
